In [1]:

import numpy as np

In [2]:
inputArray = np.array ([
    [1, 2, 3],
    [4, 5, 6]
])

In [3]:

inputArray

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
inputArray.shape

(2, 3)

In [5]:

inputArray[0][1]

np.int64(2)

In [6]:

inputArray[0][1:]

array([2, 3])

In [7]:

np.zeros (2)

array([0., 0.])

In [8]:

np.ones (3)

array([1., 1., 1.])

#### Sorting the array

In [9]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])


In [10]:

np.sort (arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

#### concat the array

In [11]:

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [12]:

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Reshape the array

In [13]:

a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [14]:
b = a.reshape(2, 3)
print(b)

[[0 1 2]
 [3 4 5]]


In [15]:

a

array([0, 1, 2, 3, 4, 5])

In [16]:

a[1:5]

array([1, 2, 3, 4])